version: '3.2'

services:
    autoheal: 
        restart: always
        image: willfarrell/autoheal
        environment: 
            - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    virtuoso:
        image: tenforce/virtuoso:virtuoso7.2.5
        volumes: 
            - type: volume
              source: virtuoso-db
              target: /data
        ports:
            - "8890:8890"
        restart: always  
    synbiohubBackend:
        image: synbiohub/sbh3backend:snapshot
        depends_on: 
            - virtuoso
        ports:
            - "6789:6789"
        volumes:
            - type: volume
              source: sbh
              target: /mnt
            - type: volume
              source: virtuoso-db
              target: /virtuoso
        dns: 8.8.8.8
        restart: always
    synbiohubFrontend:
        image: synbiohub/sbh3frontend:snapshot
        depends_on: 
            - virtuoso
        ports:
            - "3333:3333"
        volumes:
            - type: volume
              source: sbh
              target: /mnt
            - type: volume
              source: virtuoso-db
              target: /virtuoso
        dns: 8.8.8.8
        restart: always

volumes:
    virtuoso-db:
    sbh:
